In [13]:
import nfl_data_py as nfl
import pandas as pd

In [15]:
def get_seasonal_data(year):
    year_list = []
    year_list.append(int(year))
    df = nfl.import_seasonal_data(year_list)
    id_df = nfl.import_ids()
    id_df = id_df[['gsis_id','name' , 'position', 'age']]
    df = pd.merge(id_df, 
                    df,  
                     left_on = 'gsis_id',
                     right_on = 'player_id',
                     how ='right')
    # cols = df.columns.tolist()
    # cols = cols[-1:] + cols[:-2]
    # df = df[cols]
    df = df.sort_values('name')

    return df.drop(columns = ['gsis_id', 'season_type'])

latest_season = get_seasonal_data(2023)
latest_season.sample(5)

,name,position,age,player_id,season,completions,attempts,passing_yards,passing_tds,interceptions,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
352,Tim Jones,WR,25.9,00-0036497,2023,0,0,0.0,0,0.0,...,0.030846,0.132694,0.036071,0.0,0.037383,0.034188,0.018036,0.028857,0.258567,0.025310
202,Royce Freeman,RB,28.1,00-0034838,2023,0,0,0.0,0,0.0,...,0.013474,0.010417,0.006572,0.0,0.010870,0.009174,0.003286,0.005258,0.045139,0.059481
218,Khari Blasingame,RB,27.7,00-0035099,2023,0,0,0.0,0,0.0,...,0.006211,0.047195,0.001312,0.0,0.000000,0.000000,0.000656,0.001050,0.009050,0.009805
490,Daniel Bellinger,TE,23.5,00-0038115,2023,0,0,0.0,0,0.0,...,0.114923,0.150716,0.113839,0.0,0.065217,0.058824,0.056920,0.091071,0.667539,0.061994
134,Mitchell Trubisky,QB,29.6,00-0033869,2023,67,107,632.0,4,5.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.155587

In [20]:
latest_draft_picks = nfl.import_draft_picks([2023])
ids = nfl.import_ids()

In [24]:
ids.sample(5)
#remove all columns that end with _id except gsis_id from ids
bio = ids.loc[:,~ids.columns.str.endswith('_id') | ids.columns.isin(['gsis_id'])]
test = latest_season[['name', 'position', 'age', 'player_id']].merge(bio, left_on = 'player_id', right_on = 'gsis_id', how = 'left')
test.sample(5)

,name_x,position_x,age_x,player_id,gsis_id,name_y,merge_name,position_y,team,birthdate,age_y,draft_year,draft_round,draft_pick,draft_ovr,twitter_username,height,weight,college,db_season
92,Chris Manhertz,TE,32.0,00-0031484,00-0031484,Chris Manhertz,chris manhertz,TE,NYG,1992-04-10,32.0,2016.0,NaN,NaN,NaN,NaN,78.0,235.0,Canisius,2024.0
115,Craig Reynolds,RB,27.8,00-0035567,00-0035567,Craig Reynolds,craig reynolds,RB,DET,1996-06-15,27.8,2019.0,NaN,NaN,NaN,NaN,71.0,216.0,Kutztown,2024.0
155,DeVante Parker,WR,31.2,00-0031547,00-0031547,DeVante Parker,devante parker,WR,PHI,1993-01-20,31.2,2015.0,1.0,14.0,14.0,DeVanteParker09,75.0,215.0,Louisville,2024.0
195,Erik Ezukanma,WR,24.2,00-0038092,00-0038092,Erik Ezukanma,erik ezukanma,WR,MIA,2000-01-25,24.2,2022.0,4.0,20.0,125.0,NaN,74.0,206.0,Texas Tech,2024.0
544,Tyjae Spears,RB,22.8,00-0039032,00-0039032,Tyjae Spears,tyjae spears,RB,TEN,2001-06-15,22.8,2023.0,3.0,18.0,81.0,NaN,70.0,200.0,Tulane,2024.0