In [1]:
import nfl_data_py as nfl
import pandas as pd

In [3]:
def get_seasonal_data(year):
    year_list = []
    year_list.append(int(year))
    df = nfl.import_seasonal_data(year_list)
    # id_df = nfl.import_ids()
    # id_df = id_df[['gsis_id','name' , 'position', 'age']]
    # df = pd.merge(id_df, 
    #                 df,  
    #                  left_on = 'gsis_id',
    #                  right_on = 'player_id',
    #                  how ='right')
    # # cols = df.columns.tolist()
    # # cols = cols[-1:] + cols[:-2]
    # # df = df[cols]
    # df = df.sort_values('name')
    return df

    return df.drop(columns = ['gsis_id', 'season_type'])

get_seasonal_data(2019).columns

Index(['player_id', 'season', 'season_type', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr_x', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr',
       'games', 'tgt_sh', 'ay_sh', 'yac_sh', 'wopr_y', 'ry_sh', 'rtd_sh',
       'rfd_sh', 'rtdfd_sh', 'dom', 'w8dom', 'yptmpa', 'ppr_sh'],
      dtype='object')

In [20]:
latest_draft_picks = nfl.import_draft_picks([2023])
ids = nfl.import_ids()

In [24]:
ids.sample(5)
#remove all columns that end with _id except gsis_id from ids
bio = ids.loc[:,~ids.columns.str.endswith('_id') | ids.columns.isin(['gsis_id'])]
test = latest_season[['name', 'position', 'age', 'player_id']].merge(bio, left_on = 'player_id', right_on = 'gsis_id', how = 'left')
test.sample(5)

,name_x,position_x,age_x,player_id,gsis_id,name_y,merge_name,position_y,team,birthdate,age_y,draft_year,draft_round,draft_pick,draft_ovr,twitter_username,height,weight,college,db_season
92,Chris Manhertz,TE,32.0,00-0031484,00-0031484,Chris Manhertz,chris manhertz,TE,NYG,1992-04-10,32.0,2016.0,NaN,NaN,NaN,NaN,78.0,235.0,Canisius,2024.0
115,Craig Reynolds,RB,27.8,00-0035567,00-0035567,Craig Reynolds,craig reynolds,RB,DET,1996-06-15,27.8,2019.0,NaN,NaN,NaN,NaN,71.0,216.0,Kutztown,2024.0
155,DeVante Parker,WR,31.2,00-0031547,00-0031547,DeVante Parker,devante parker,WR,PHI,1993-01-20,31.2,2015.0,1.0,14.0,14.0,DeVanteParker09,75.0,215.0,Louisville,2024.0
195,Erik Ezukanma,WR,24.2,00-0038092,00-0038092,Erik Ezukanma,erik ezukanma,WR,MIA,2000-01-25,24.2,2022.0,4.0,20.0,125.0,NaN,74.0,206.0,Texas Tech,2024.0
544,Tyjae Spears,RB,22.8,00-0039032,00-0039032,Tyjae Spears,tyjae spears,RB,TEN,2001-06-15,22.8,2023.0,3.0,18.0,81.0,NaN,70.0,200.0,Tulane,2024.0

In [39]:
# #Scrape seasonal data from 2019 to 2023
# seasons = []
# for i in range(2019, 2024):
#     seasons.append(get_seasonal_data(i))
# seasons = pd.concat(seasons)
#Remove rows where name is null
df = seasons[seasons['name'].notnull()]
#Remove rows where position is not QB, RB, WR, TE
df = df[df['position'].isin(['QB', 'RB', 'WR', 'TE'])]
df.sample(5)

,name,position,age,player_id,season,completions,attempts,passing_yards,passing_tds,interceptions,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
168,Ameer Abdullah,RB,30.8,00-0032104,2020,0,0,0.0,0,0.0,...,0.070156,0.059688,0.032420,0.125000,0.043011,0.055046,0.078710,0.050936,0.267281,0.044159
265,Sony Michel,RB,29.0,00-0034845,2022,0,0,0.0,0,0.0,...,0.031989,0.053267,0.019414,0.000000,0.007692,0.006849,0.009707,0.015531,0.126794,0.026685
93,Kenjon Barner,RB,33.8,00-0030465,2020,0,0,0.0,0,0.0,...,0.000000,0.032609,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
385,Cooper Kupp,WR,30.8,00-0033908,2019,0,1,0.0,0,0.0,...,0.237004,0.477414,0.248661,0.454545,0.229730,0.250000,0.351603,0.289838,1.837025,0.180266
36,Jared Cook,TE,37.0,00-0027061,2019,0,0,0.0,0,0.0,...,0.134320,0.361543,0.186656,0.290323,0.163265,0.180617,0.238489,0.207389,1.410000,0.120263

In [30]:
general_cols = ['name', 'position', 'age', 'team', 'player_id', 'season', 'games', 'fantasy_points', 'fantasy_points_ppr']

passing_cols = ['completions','attempts', 'passing_yards', 'passing_tds', 'interceptions', 'sacks',
                'sack_yards', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards','passing_yards_after_catch', 
                'passing_first_downs', 'passing_epa','passing_2pt_conversions', 'pacr', 'dakota']

rushing_cols = ['rushing_attempts', 'rushing_yards', 'rushing_tds', 'rushing_first_downs', 'rushing_epa', 
                'rushing_2pt_conversions',  'rushing_fumbles_lost','rushing_first_downs', ]

receiving_cols = ['targets', 'receptions', 'receiving_yards', 'receiving_tds', 'receiving_air_yards', 
                  'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 
                  'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_2pt_conversions', 
                  'racr', 'target_share', 'air_yards_share']

In [43]:
#filter for rows of bio where gsis_id is in the 'player_id' column of df 
player_bio = bio[bio['gsis_id'].isin(df['player_id'])]
#drop the following columns: 'twitter_username', 'merge_name', 'college', 'db_season'
player_bio = player_bio.drop(columns = ['twitter_username', 'merge_name', 'college', 'db_season'])

In [47]:
df.to_csv('../data/nfl_data_py/seasonal_data_2019_2023.csv', index = False)
player_bio.to_csv('../data/nfl_data_py/player_bio_2019_2023.csv', index = False)